server:
  port: 1238
  servlet:
      context-path: /
tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 10
    background-processor-delay: 30
    basedir: ${user.home}/tomcat/

grpc:
  server:
    port: 6007
  client:
    schedule-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  #aop:
  #auto: true
  #proxy-target-class: true
  application:
    name: schedule-client-server
  sleuth:
    sampler:
      probability: 1
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
     multipart:
      max-file-size: 1000000000
      max-request-size: 1000000000
  datasource:
      #driver-class-name: com.xugu.cloudjdbc.Driver
      #url: jdbc:xugu://10.40.16.44:31293/babjbdb?char_set=utf8
      #username: sod5
      #password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.1.6.117:8000/sod
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      #maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        #dialect: com.xugu.dialect.XuguDialect5
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    #database: mysql
    open-in-view: false
  redis:
    password: Cmadaas@2019
    cluster:
      nodes: 10.1.100.33:6378,10.1.100.33:6380,10.1.100.33:6381,10.1.100.34:6382,10.1.100.34:6383,10.1.100.34:6384
      max-redirects: 3
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
#    host: 10.1.6.117
#    port: 8001
#    timeout: 5000
#    password:
mybatis:
  type-aliases-package: com.piesat.*.entity
  mapper-locations: classpath:mapper/*.xml
  callSettersOnNulls:  true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.1.6.117:8002/eureka/

backup:
  temp-path: /zzj/CMADASS

gbaseserver:
  ip: 127.0.0.1
  user: gbase
  pass: gbase
EIDIURL: http://10.20.67.139/store/openapi/v2/logs/push_batch?apikey=e10adc3949ba59abbe56e057f2gg88dd
TRANSFERURL: http://127.0.0.1:29999/transfer
log:
  path: E:/log
  level: INFO
jasypt:
  encryptor:
    password: HT95279527